### ISSUE TITLE
Question: How do I provide a file that I want to reference on `swipl` initialisation.

### ISSUE THREAD

**Issue by jeswr** [rla/npm-swipl-wasm#11]
Possibly a stupid question; but I am wanting to do the equivalent of executing in the command line.
```
swipl -f eye.pl -g main -- --version
```

I believe this should look something like

```ts
import { SWIPLModule } from 'swipl-wasm/dist/common';
import { queryOnce, runQuery, SWIPL, writeEye } from '..';

(async () => {
  const Module: SWIPLModule = await SWIPL({ print: (s: string) => {
    console.log(s);
  }, arguments: ['-f', 'eye.pl', '-g', 'main', '--', '--version'] } as EmscriptenModule);

})();
```

But I am not sure how to do the `Module.fs.writeFile('eye.pl', ...)` logic before those arguments are called. Any insights on how to achieve this?

This question is based on https://github.com/eyereasoner/eye-js/issues/20

**Comment by rla** [comment]
There seems to be no documented option to provide prepared virtual filesystem object with Emscripten.

Maybe updating the virtual filesystem would work? In one of the Emscripten hook calls, possibly:
https://emscripten.org/docs/api_reference/module.html#Module.onRuntimeInitialized

**Comment by jeswr** [comment]
Aha - thanks! `preRun` worked

```ts

(async () => {
  const Module: SWIPLModule = await SWIPL({ arguments: ['-q', '-f', 'eye.pl'], preRun: writeEye });
  queryOnce(Module, 'main', ['--image', 'eye.pvm']);
  fs.writeFileSync(path.join(__dirname, '..', 'eye', 'eye.pvm'), Module.FS.readFile('eye.pvm'));
})();
```
